#%RAML 1.0
title: DORD-cat
version: 1.0
baseUri: http://localhost:3000
mediaType: application/json
/cat:
    post:
        description: 创建分类
        (handlerFunc): createCat
        (groupBy): auth
        body:
          application/json:
            type: createCat
            example: !include json/createCat.req.json
    /root:
      get:
          description: 获取第一级分类
          (handlerFunc): rootCat
          (groupBy): cat
    /:id:
        uriParameters:
            id: ID
        delete:
            description: 删除单个分类
            (handlerFunc): deleteCat
            (groupBy): auth
        /child:
            get:
                description: 获取分类的子集分类
                (handlerFunc): getCatChild
                (groupBy): cat
        /info:
            get:
                description: 获取单个分类信息
                (handlerFunc): getCatInfo
                (groupBy): cat
            put:
                description: 修改单个分类信息
                (handlerFunc): putCatInfo
                (groupBy): auth
        /sku:
            get:
                description: 获取分类下所有产品
                (handlerFunc): getCatSkus
                (groupBy): cat
